name: /home/groups/hoolock2/u0/jg/thesis/env/methylseq
channels:
  - bioconda
  - conda-forge
  - r
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=4.5
  - _r-mutex=1.0.1
  - alsa-lib=1.1.5
  - bedtools=2.29.2
  - binutils_impl_linux-64=2.34
  - binutils_linux-64=2.34
  - bioconductor-biobase=2.46.0
  - bioconductor-biocgenerics=0.32.0
  - bioconductor-biocparallel=1.20.0
  - bioconductor-biostrings=2.54.0
  - bioconductor-delayedarray=0.12.0
  - bioconductor-genomeinfodb=1.22.0
  - bioconductor-genomeinfodbdata=1.2.2
  - bioconductor-genomicalignments=1.22.0
  - bioconductor-genomicranges=1.38.0
  - bioconductor-iranges=2.20.0
  - bioconductor-rhtslib=1.18.0
  - bioconductor-rsamtools=2.2.0
  - bioconductor-rtracklayer=1.46.0
  - bioconductor-s4vectors=0.24.0
  - bioconductor-summarizedexperiment=1.16.0
  - bioconductor-xvector=0.26.0
  - bioconductor-zlibbioc=1.32.0
  - bismark=0.22.3
  - bowtie2=2.3.5.1
  - bwidget=1.9.14
  - bz2file=0.98
  - bzip2=1.0.8
  - ca-certificates=2020.4.5.1
  - cairo=1.16.0
  - certifi=2020.4.5.1
  - cffi=1.14.0
  - chardet=3.0.4
  - click=7.1.1
  - coloredlogs=14.0
  - colormath=3.0.0
  - cryptography=2.8
  - curl=7.68.0
  - cutadapt=2.6
  - cycler=0.10.0
  - decorator=4.4.2
  - dnaio=0.3
  - fastqc=0.11.9
  - font-ttf-dejavu-sans-mono=2.37
  - fontconfig=2.13.1
  - freetype=2.10.1
  - fribidi=1.0.9
  - future=0.18.2
  - gcc_impl_linux-64=7.3.0
  - gcc_linux-64=7.3.0
  - gettext=0.19.8.1
  - gfortran_impl_linux-64=7.3.0
  - gfortran_linux-64=7.3.0
  - giflib=5.2.1
  - glib=2.58.3
  - graphite2=1.3.13
  - gsl=2.6
  - gxx_impl_linux-64=7.3.0
  - gxx_linux-64=7.3.0
  - harfbuzz=2.4.0
  - hisat2=2.2.0
  - humanfriendly=8.1
  - icu=64.2
  - idna=2.9
  - jinja2=2.11.2
  - jpeg=9c
  - kiwisolver=1.2.0
  - krb5=1.16.4
  - lcms2=2.9
  - ld_impl_linux-64=2.34
  - libblas=3.8.0
  - libcblas=3.8.0
  - libcurl=7.68.0
  - libdeflate=1.0
  - libedit=3.1.20170329
  - libffi=3.2.1
  - libgcc-ng=9.2.0
  - libgfortran-ng=7.3.0
  - libgomp=9.2.0
  - libiconv=1.15
  - liblapack=3.8.0
  - libopenblas=0.3.9
  - libpng=1.6.37
  - libssh2=1.8.2
  - libstdcxx-ng=9.2.0
  - libtiff=4.1.0
  - libuuid=2.32.1
  - libwebp-base=1.1.0
  - libxcb=1.13
  - libxml2=2.9.10
  - llvm-openmp=10.0.0
  - lz4-c=1.9.2
  - lzstring=1.0.4
  - make=4.3
  - markdown=3.2.1
  - markupsafe=1.1.1
  - matplotlib-base=3.1.1
  - multiqc=1.8
  - ncurses=6.1
  - networkx=2.2
  - numpy=1.18.1
  - openjdk=11.0.1
  - openssl=1.1.1f
  - pandas=1.0.3
  - pandoc=2.9.2.1
  - pango=1.42.4
  - pcre=8.44
  - perl=5.26.2
  - pigz=2.3.4
  - pip=20.0.2
  - pixman=0.38.0
  - pthread-stubs=0.4
  - pycparser=2.20
  - pyopenssl=19.1.0
  - pyparsing=2.4.7
  - pysocks=1.7.1
  - python=3.6.10
  - python-dateutil=2.8.1
  - python_abi=3.6
  - pytz=2019.3
  - pyyaml=5.3.1
  - r-askpass=1.1
  - r-assertthat=0.2.1
  - r-backports=1.1.6
  - r-base=3.6.3
  - r-base64enc=0.1_3
  - r-bh=1.72.0_3
  - r-bitops=1.0_6
  - r-broom=0.5.5
  - r-callr=3.4.3
  - r-cellranger=1.1.0
  - r-cli=2.0.2
  - r-clipr=0.7.0
  - r-colorspace=1.4_1
  - r-cowplot=1.0.0
  - r-crayon=1.3.4
  - r-curl=4.3
  - r-dbi=1.1.0
  - r-dbplyr=1.4.2
  - r-digest=0.6.25
  - r-dplyr=0.8.5
  - r-ellipsis=0.3.0
  - r-evaluate=0.14
  - r-fansi=0.4.1
  - r-farver=2.0.3
  - r-forcats=0.5.0
  - r-formatr=1.7
  - r-fs=1.4.1
  - r-futile.logger=1.4.3
  - r-futile.options=1.0.1
  - r-generics=0.0.2
  - r-ggplot2=3.2.1
  - r-ggpubr=0.2.5
  - r-ggrepel=0.8.2
  - r-ggsci=2.9
  - r-ggsignif=0.6.0
  - r-glue=1.4.0
  - r-gridextra=2.3
  - r-gtable=0.3.0
  - r-haven=2.2.0
  - r-highr=0.8
  - r-hms=0.5.3
  - r-htmltools=0.4.0
  - r-httr=1.4.1
  - r-jsonlite=1.6.1
  - r-kableextra=1.1.0
  - r-knitr=1.28
  - r-labeling=0.3
  - r-lambda.r=1.2.4
  - r-lattice=0.20_41
  - r-lazyeval=0.2.2
  - r-lifecycle=0.2.0
  - r-lubridate=1.7.8
  - r-magrittr=1.5
  - r-markdown=1.1
  - r-mass=7.3_51.5
  - r-matrix=1.2_18
  - r-matrixstats=0.56.0
  - r-mgcv=1.8_31
  - r-mime=0.9
  - r-modelr=0.1.6
  - r-munsell=0.5.0
  - r-nlme=3.1_147
  - r-openssl=1.4.1
  - r-pillar=1.4.3
  - r-pkgconfig=2.0.3
  - r-plogr=0.2.0
  - r-plyr=1.8.6
  - r-polynom=1.4_0
  - r-prettyunits=1.1.1
  - r-processx=3.4.2
  - r-progress=1.2.2
  - r-ps=1.3.2
  - r-purrr=0.3.3
  - r-r6=2.4.1
  - r-rcolorbrewer=1.1_2
  - r-rcpp=1.0.4.6
  - r-rcurl=1.98_1.1
  - r-readr=1.3.1
  - r-readxl=1.3.1
  - r-rematch=1.0.1
  - r-reprex=0.3.0
  - r-reshape2=1.4.4
  - r-rlang=0.4.5
  - r-rmarkdown=2.1
  - r-rstudioapi=0.11
  - r-rvest=0.3.5
  - r-scales=1.1.0
  - r-selectr=0.4_2
  - r-snow=0.4_3
  - r-stringi=1.4.6
  - r-stringr=1.4.0
  - r-sys=3.3
  - r-tibble=3.0.0
  - r-tidyr=1.0.2
  - r-tidyselect=1.0.0
  - r-tidyverse=1.3.0
  - r-tinytex=0.21
  - r-utf8=1.1.4
  - r-vctrs=0.2.4
  - r-viridislite=0.3.0
  - r-webshot=0.5.2
  - r-whisker=0.4
  - r-withr=2.1.2
  - r-xfun=0.13
  - r-xml=3.99_0.3
  - r-xml2=1.3.1
  - r-yaml=2.2.1
  - r-zeallot=0.1.0
  - readline=8.0
  - requests=2.23.0
  - samtools=1.9
  - sed=4.7
  - setuptools=46.1.3
  - simplejson=3.8.1
  - six=1.14.0
  - spectra=0.0.11
  - sqlite=3.30.1
  - tbb=2020.1
  - tk=8.6.10
  - tktable=2.10
  - tornado=6.0.4
  - trim-galore=0.6.5
  - urllib3=1.25.8
  - wheel=0.34.2
  - xlrd=1.2.0
  - xopen=0.7.3
  - xorg-fixesproto=5.0
  - xorg-inputproto=2.3.2
  - xorg-kbproto=1.0.7
  - xorg-libice=1.0.10
  - xorg-libsm=1.2.3
  - xorg-libx11=1.6.9
  - xorg-libxau=1.0.9
  - xorg-libxdmcp=1.1.3
  - xorg-libxext=1.3.4
  - xorg-libxfixes=5.0.3
  - xorg-libxi=1.7.10
  - xorg-libxrender=0.9.10
  - xorg-libxtst=1.2.3
  - xorg-recordproto=1.14.2
  - xorg-renderproto=0.11.1
  - xorg-xextproto=7.3.0
  - xorg-xproto=7.0.31
  - xz=5.2.5
  - yaml=0.2.3
  - zlib=1.2.11
  - zstd=1.4.4

